version: '3.8'

services:

  racecar:
    build: .
    image: racecar/racecar:latest
    ports:
      - 6080:6080
      - 11311:11311
    entrypoint: ./.entrypoint.sh
    volumes:
      - ./home:/home/racecar

    extra_hosts:
      racecar: 127.0.0.1
