version: '3.8'

services:
  arcturus:
    build: .
    image: toyat522/arcturus
    ports:
      - 6080:6080 # VNC
      - 11311:11311 # ROS master
    entrypoint: entrypoint.sh
    volumes:
      - ./home:/home/arcturus
